name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

 # Remove this step if you're not using Jekyll or modify it
    # if you're building your files with a different system
    - name: Build Jekyll Files
      run: |
        docker run \
        -v $new:/srv/jekyll -v $new/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --trace"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAWH57VGWOKV6AP7AT'
        aws-secret-access-key: 'egxnDsQPMm+V342Ojsb2SVrW12zNvv/ueWeK7fiY'
        aws-region: us-east-1 # Change this to the location of your S3 Bucket

    # Change ./_site/ to the location of your website in your repository,
    # with Jekyll _site/ is the default location of the built files
    - name: Deploy to S3 bucket
      run: aws s3 sync .github/ ${{secrets.S3_BUCKET}}

    # Remove this step if you're not using CloudFront
    - name: Invalidate CloudFront Objects
      run: aws cloudfront create-invalidation --distribution-id 'E1YDJQP52Q7V26' --path "/*"